name: my_ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'  # Updated SDK version range

dependencies:
  flutter:
    sdk: flutter
  # Utility packages
  http: ^1.2.1  # Latest version
  intl: ^0.19.0  # Latest version
  logger: ^2.3.0  # Latest version
  lottie: ^3.1.2
  url_launcher: ^6.2.6  # Latest version
  connectivity_plus: ^6.0.3
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  # State management
  get: ^4.6.5
  get_storage: ^2.1.1
  # Product specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  # firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/images/reviews/
    - assets/icons/payment_methods/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/poppins-SemiBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins-LightItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins-BoldItalic.ttf
          weight: 800
          style: italic
