// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1x-6oj8vKZBS9COJ0HWzf6AKx4AkM0Wg',
    appId: '1:548465130338:web:3ecc75be5dba7ffcf70a3b',
    messagingSenderId: '548465130338',
    projectId: 'ecommerceapp-41d16',
    authDomain: 'ecommerceapp-41d16.firebaseapp.com',
    storageBucket: 'ecommerceapp-41d16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiMOLirn2btIClrHmM5RVgsBlp7TFPQYA',
    appId: '1:548465130338:android:3920036b2ac79de5f70a3b',
    messagingSenderId: '548465130338',
    projectId: 'ecommerceapp-41d16',
    storageBucket: 'ecommerceapp-41d16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPpU3yYwS4ufsGntDhadqPNyMPPcFhswI',
    appId: '1:548465130338:ios:a1b4a6cf85ce99c5f70a3b',
    messagingSenderId: '548465130338',
    projectId: 'ecommerceapp-41d16',
    storageBucket: 'ecommerceapp-41d16.appspot.com',
    androidClientId: '548465130338-l26o5dd0lcmrbl51l8l20hkn01bmelqm.apps.googleusercontent.com',
    iosClientId: '548465130338-64sqfk3i5d0pc4o6fsihqtgdr9do111q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myEcommerceApp',
  );

}